### ISSUE TITLE
[Public Profile] - Create public profile pages for each user with the url pattern `/profile/[username]`

### ISSUE THREAD

**Issue by nspilman** [nspilman/eptss-site#16]
**Feature Requirements -** 
- Every user who has participated in a round should have a public profile. 
- One can access this profile by going to `/profile/<username>`
- This profile should include tabular details for 
	- what rounds they signed up for
	- Their round submissions
	- If the song they signed up with ended up being the song of the round 

**Suggested Technical Direction** - 
- Database - create new Postgres views for the public data by username. 
- Pages - build Static pages for each user. We will need to rebuild the website more regularly to keep these up to date, but that's okay.

**Comment by nspilman** [comment]
This is going to require the concept of a Username, unless we want to expose the user's ID or email address, which I don't.

**Comment by BBtxt** [comment]
Would we want to only statically make public profile pages for users that have submitted a url for a round? I was going to make the paths for all users that have signed up. I could see once we get more users who don't participate we could make collect more data than needed. The other page views are perfect

**Comment by nspilman** [comment]
Yeah, let's make a page for every user who's signed up, with a placeholder for sections with zero data - so no submissions.
