### ISSUE TITLE
[Public Profile] - Link to end user's public profile from Round page 

### ISSUE THREAD

**Issue by nspilman** [nspilman/eptss-site#36]
Update round page to show each individual end user's submission. 
Click on the end user to access their profile page.

**Comment by BBtxt** [comment]
I'm planning on lumping all the features together in one pr

**Comment by nspilman** [comment]
Completed in this commit - https://github.com/nspilman/eptss-site/commit/9e345e6d7efdcf9f9e316e051333d3eb7ca89226
